#ifndef PACKETDISPATCHER_GLOBAL_H
#define PACKETDISPATCHER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PACKETDISPATCHER_LIBRARY)
#define PACKETDISPATCHER_EXPORT Q_DECL_EXPORT
#else
#define PACKETDISPATCHER_EXPORT Q_DECL_IMPORT
#endif

#endif // PACKETDISPATCHER_GLOBAL_H
